### ISSUE TITLE
operator: install iscsi - design

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#1]
ref - https://gist.github.com/jjo/1ccade2ea3ae05c5825fd37c8722d4f6

### Draft - 0
```yaml
kind: Command
apiVersion:
metadata:
  name:
  annotations:
    cmd: &cmd apt-get update -qy && apt-get install -qy tgt ceph-fs-common ceph-common xfsprogs
spec:
  hostPID: true
  securityContext:
    privileged: true
  image: alpine:3.7
  command:
    - nsenter
    - --mount=/proc/1/ns/mnt
    - --
    - sh
    - -c
    - *cmd
```

**Comment by AmitKumarDas** [comment]
### Thoughts 1
- A operator that listens to kind Command
- This operator spins up a K8s DaemonJob with characteristics described in Command specs
- This image understands kind Command & executes the Command specs
- This image publishes the results as kind CommandResult
- Operator aggregates the CommandResult(s) & publishes the success, failure, counts, etc at Command's status field

### Draft 1
```yaml
kind: Command
metadata:
spec:
  hostPID:
  securityContext:
  command:
  -
status:
  phase:
  totalCount:
  passCount:
  failCount:
  errMsgs:
  -
```

**Comment by AmitKumarDas** [comment]
### UseCases
- Find a way to detect presence of iscsi utils in k8s worker nodes
- Ability to install or upgrade iscsi utils in k8s worker nodes
- Ability to execute 3rd party cli tools
  - e.g. ability to execute https://github.com/sumitnagal/test-tools/pull/1

**Comment by vharsh** [comment]
A long time ago, I once looked at a PR in Ansible, which was being used to figure out the hostname, well it turns out not everyone follows the sane POSIX standards(take package management for example, it's a mess, `yum`, `apt`, `dnf`, if I exclude people from the ArchLinux and Gentoo world).
Some organizations might even end up running [their own software repositories](http://www.iitk.ac.in/july14cse/official-linux-mirror) thankfully some of them keep them in sync, some don't(I hope people don't like to rename packages to make it harder for us).

Besides, considering the number of packages out in the wild would we prefer to redo the work done by awesome tools like `brew` on MacOS, `LinuxBrew` on Linux, etc?
Is building stuff from source by pulling it from somewhere the only ONE way to do it?

**Comment by AmitKumarDas** [comment]
@vharsh We would like to detect/monitor, & eventuall install/uninstall/upgrade host packages. This issue talks about iscsi-utils for example. Having said that, we would like to go for GitOps way for this requirement. 

We wont be building source rather we want to put binaries in place to execute its commands. These commands are in turn specified in K8s CR i.e. Command. For installing iscsi, we can use our go binary that will just run binaries present on the host. 

Now think for example, running a custom python binary via this approach. In order to do so, we would have to get the python binary along with our base docker image & our own go based executor that reads this Command CR & executes the commands exposed out of this python binary. OTH this entire stuff boils down to an image that needs to be provided to this Command CR. This Command CR would in-turn create a Job/Pod that 1/ makes use of this image & 2/ provide the commands that needs to be executed by this image.

**Comment by AmitKumarDas** [comment]
@vharsh to be more specific, we are not re-inventing anything here. We are packaging in a way that is native to K8s & is more GitOps friendly. So a Mac based k8s worker node can use `brew xyz` in the Command CR.

**Comment by vharsh** [comment]
Okay, from Director perspective a user might want to happen automatically(this is a dangerous word and IMO an end user in prod wouldn't trust any pod to take permissions to run stuff on Node by reading thing off a cfgmap, a rouge user like me might edit the cfgmap, add `sudo shutdown now` and kill the executor pod(conditioned to my permissions in the cluster) and then the stateful workloads will go for a toss(if shutdown doesn't have a graceful wait period).

**Comment by AmitKumarDas** [comment]
Yes. Agree. However this needs to be channelized via authentication and authorisation policies. I believe starting off with kubernetes namespaced scope and rbac should be a good start.

**Comment by AmitKumarDas** [comment]
On a different note, we can use this for chaos tests. 🤓

**Comment by AmitKumarDas** [comment]
Thinking further I guess we will expose the final product i.e. the docker image that does just one thing e.g. detect iscsi and install the same. Obviously there will be lots of docker images one for each distro.

The mechanics of the design will remain flexible though to build any kind of product/image.

**Comment by AmitKumarDas** [comment]
This final image depending on its criticality can be made to run only from kube-system namespace if this makes things secure. In other words an image only for cluster admins and no one else

**Comment by AmitKumarDas** [comment]
Some references:

- https://github.com/piontec/netperf-operator
- https://github.com/portworx/fio-tools
- https://github.com/pingcap/chaos-mesh/tree/master/controllers/iochaos
- https://github.com/rancher/system-upgrade-controller

**Comment by AmitKumarDas** [comment]
### Draft specs:
```yaml
kind: Command
spec:
  enabled:
    when: Once # Never, Always
  jobTemplate:
  commands:
  - name:
    desc:
    cmd:
status:
  phase:
  outputs:
    <commandname>:
```
### How it works?
- Controller watches Command resource
- Controller create a Job based on podTemplate
- This Job's annotation has the details of the Command resource
- This Job makes use of a binary that picks the Command specs from its own Pod
- This binary runs the commands & stores its outputs
- This binary updates the Command resource with the outputs
- A Command can be run only once or multiple times
- A Command should be run by a single controller instance at any point in time
- Once the Command status is updated, the completed Job is deleted
- A Command can be re-run if it is meant to be run always
