### ISSUE TITLE
design: recipe should differentiate between action, action on collection & bulk action

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#123]
```yaml
kind: Recipe
spec:
  tasks:
  - assert:
  - assertAll:
  - bulkAssert:
  - delete:
  - deleteAll:
  - bulkDelete:
```
Where:
- action implies an action against a single resource instance
- actionAll implies actions against one or more resource instances of same apiversion, kind & namespace
- bulkAction implies actions against one or more resources belonging to one or more apiversion, kind & namespace combinations
