### ISSUE TITLE
feat: add clone action to recipe

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#127]
```yaml
kind: Recipe
spec:
  tasks:
  - name:
    clone:
      # state will provide apiversion, kind to filter the gvk
      # name is mandatory
      state:
      generate: 
        name:
        namespace:
        nameReplicas: # these many names i.e. resources will get created
        namespaceReplicas: # these many namespaces will get created
```
```yaml
kind: Recipe
spec:
  tasks:
  - name:
    cloneAll:
      apiVersion:
      kind:
      labelSelector: 
      generate:
        name:
        namespace:
        nameReplicas:
        namespaceReplicas:
```
```yaml
kind: Recipe
spec:
  tasks:
  - name:
    bulkClone:
      resources:
      - apiVersion:
        kind:
      labelSelector: 
      generate:
        name:
        namespace:
        nameReplicas:
        namespaceReplicas:
```
