### ISSUE TITLE
feat: apply one or more resources against a group of nodes

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#153]
**ProblemStatement**: As a SRE admin, I want to apply resource(s) of a given Kind against a group of nodes based on node selector / labels. For example, I want to run a Pod each on Nodes N1, N2 & N3.

**Comment by AmitKumarDas** [comment]
### Draft Design
```yaml
kind: Recipe
spec:
  tasks:
  - applyNodeGroup:
    nodeSelector:
      key: value
    state:
      kind: Pod
      metadata:
        name:
        namespace:
      spec:
```
### NOTE
- Considering running a Pod across a group of Nodes
  - When a new node gets added a new Pod should run on that Node
  - When an existing node is removed from the label selector group, corresponding Pod should be deleted
