### ISSUE TITLE
feat: get required fields from a resource

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#155]
**_ProblemStatement_**: As a SRE admin, I want to fetch required fields from a particular resource. For example, I want to fetch the replicas from the Deployment `abc` running in `def` namespace.

**Comment by AmitKumarDas** [comment]
### Draft design
```yaml
kind: Recipe
spec:
  tasks:
  - name: get-replicas-from-deployment
    get:
      state:
        kind: Deployment
        metadata:
          name: abc
          namespace: def
        spec: 
          replicas: ?
```
- Above when applied will result in below
```yaml
kind: Recipe
spec:
  # removed for brevity
status:
  tasks:
    get-replicas-from-deployment:
      object:
        kind: Deployment
        metadata:
          name: abc
          namespace: def
        spec: 
          replicas: 2
```
