### ISSUE TITLE
feat: get required fields from a list of resources belonging to same Kind

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#156]
**_ProblemStatement_**: As a SRE admin, I want to fetch required fields from all resources belonging to the same Kind. For example, I want to fetch the replicas from all Deployments with labels `my-app: nginx` and running in `ent` namespace.

**Comment by AmitKumarDas** [comment]
### Draft design
```yaml
kind: Recipe
spec:
  tasks:
  - name: list-replicas-from-deployment
    get:
      state:
        kind: Deployment
        metadata:
          namespace: ent
          labels:
            my-app: nginx
        spec: 
          replicas: ?
```
- Above when applied will result in below
```yaml
kind: Recipe
spec:
  # removed for brevity
status:
  tasks:
    list-replicas-from-deployment:
      objectList:
      - kind: Deployment
        metadata:
          name: abc
          namespace: ent
          labels:
            my-app: nginx
        spec: 
          replicas: 2
      - kind: Deployment
        metadata:
          name: abc
          namespace: ent
          labels:
            my-app: nginx
        spec: 
          replicas: 3
```
