### ISSUE TITLE
feat: delete previously created resources that are no longer needed

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#157]
**_ProblemStatement_**:  As a SRE admin, I would like to delete outdated resources that were created via Recipe tasks. I want to avoid creating new Recipe(s) to delete unused ones.

**Comment by AmitKumarDas** [comment]
### Draft design
- Consider below Recipe was applied previously
```yaml
kind: Recipe
metadata:
  name: auto
  namespace: reconcile
spec:
  tasks:
  - name:
    create:
      state:
        kind: Pod
        metadata: 
          name: hello
          name: there
  - name:
    apply:
      state:
        kind: ConfigMap
        metadata: 
          name: hello
          name: there
```
- Above Recipe was modified as follows:
```yaml
kind: Recipe
metadata:
  name: auto
  namespace: reconcile
spec:
  tasks:
  - name:
    apply:
      state:
        kind: ConfigMap
        metadata: 
          name: hello
          name: there
```
- Above should lead to deletion of Pod that was created earlier by this Recipe
