### ISSUE TITLE
feat: add/remove labels to resources of same kind

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#158]
**_ProblemStatement_**: As a SRE admin, I want to add or remove labels against resources based on resource names or resource labels

**Comment by AmitKumarDas** [comment]
### Draft Design
```yaml
kind: Recipe
spec:
  tasks:
  - applyLabels:
      state:
```
