### ISSUE TITLE
feat: resource pipe

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#23]
ResourcePipe is a custom resource that extracts values from one or more k8s resources and manages to build & then apply a new k8s resource in the k8s cluster.

```yaml
kind: ResourcePipe
spec:
  input:
  - apiVersion:
    resource:
    name:
    namespace:
    get:
    - key:
      path:
      default:
  output:
    state:
    set:
    - key:
      path:
```

**Comment by AmitKumarDas** [comment]
Check if a tunable should be provided to preserve the changes from user. In other words both controller as well as user should be able to do changes to the same resource here output resource.

**Comment by AmitKumarDas** [comment]
Is it possible to create a resource i.e. output without any inputs.

**Comment by AmitKumarDas** [comment]
Is it possible to create a copy from an input by providing input name, namespace, apiVersion & kind

**Comment by AmitKumarDas** [comment]
More draft designs:
```yaml
spec:
  build:
    state:
      kind: Deployment
      apiVersion: apps/v1
    from:
    - state:
        kind: MyDeploy
        apiVersion: apps/v1
        metadata:
          name: amitd
          namespace: default
    set:
    - state: spec.replicas      # optional
      from: [0].spec.replicas

  
  build:
    state:
      kind: Deployment
      apiVersion: apps/v1
    from:
    - state:
        kind: MyDeploy
        apiVersion: apps/v1
        metadata:
          name: amitd
          namespace: default
    set:
    - state: spec.replicas      # optional
      from: spec.replicas
```

**Comment by AmitKumarDas** [comment]
```yaml
kind: ResourceBuilder
spec:
  state:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: abc
      namespace: abcd
    spec:
      replicas: 2
  from:
  - kind: MyDeploy
    apiVersion: apps/v1
    metadata:
      name: amitd
      namespace: default
  merge:
  - state: # optional
    path: spec.replicas  # optional
    from:
      kind: # optional if from has only one item
      apiVersion: # optional if from has only one item
      name: # optional if from has only one item
      namespace: # optional if from has only one item
      path:
```
