### ISSUE TITLE
recipe: extract value(s) declaratively

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#3]
Figure out a way/approach to extract value from specific fields in a declarative manner.

One of the approaches that we might want to follow is to find the _diff_ of the declared indent against the actual specifications. We might probably be able to get the specific field's actual value by comparing it against a dummy value. 

For example for following declaration, we should be able to find the actual _status.phase_ value of my-pod:
```yaml
kind: Pod
apiVersion: v1
metadata:
  name: my-pod
status:
  phase: WHAT
```

References:
- https://github.com/go-test/deep
-
