### ISSUE TITLE
proposal(sts): group volumes from a single statefulset

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#45]
**_ProblemStatement_**: A statefulset can be deployed with multiple replicas. In addition, each replica can be configured to use one or more persistent volumes. While due care can be taken to spread the statefulset application replicas across zones or nodes, similar strategy needs to be followed for these replicas' backing volume(s). It will be good to ensure these volumes are spread out & are never placed on a single node or single zone.

**_Possible Solution_**: Specific statefulsets can be watched _(via k8s controllers)_ & their corresponding volume claims can be tracked. The volume claims can further be filtered based on the storage class. Once required details are achieved, these information can be saved in a new custom resource. This should ensure storage provisioners to run through their volume placement decisions.

```yaml
# This custom resource will select statefulset whose volume info need
# to tracked & saved
kind: StatefulsetVolumePolicy
spec:
   select:
     matchLabels:
     matchAnnotations:
     matchFields:
   placement:
     spread: # Zone, Host
     topology:
       hosts:
       - host 2
       - host 3
```

```yaml
kind: VolumeGroup
spec:
   refer:
      kind: StatefulSet
      apiVersion: apps/v1
      name: my-sts
      namespace: my-ns
  volumes:
  - pvcName:
    podName:
    nodeName:
```
