### ISSUE TITLE
proposal: data management as a service apis

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#46]
In this issue, we shall design various custom resources that will eventually build DMAAS (data management as a service)

**Comment by AmitKumarDas** [comment]
```yaml
apiVersion: v1alpha1
kind: DataProtectionSchedule
metadata:
  name:
  namespace:
  annotations:
  labels:
spec:

  # ---------------------------------
  # scheduled backup specs
  # ---------------------------------
  schedule:
    type: # onetime or periodicfull or incremental
    cronTime: * * * * *
    retentionCount:
    ttl:
    backupType: #restic or plugin

  # ---------------------------------
  # resources that needs to be backed up based on schedule
  # ---------------------------------
  resource:
    # location to upload volume snapshots
    volumeBackupLocation:
    - 
    # resource selector will select any kubernetes resource meant to be backed up
    # it can be pod, secret, configmap, custom resources, pvc, pv etc
    resourceSelector: 
    - matchLabels:
      matchAnnotations:
      matchFields:

  pause: # true / false
 
status:
  phase: # InProgress / Completed / Error / Paused
  reason:
  message:
  schedule:
    previousTimestamp:
    nextTimestamp:
    count:
    status:
  backups:
    previousTimestamp:
    nextTimestamp:
    count:
    status:
```
