### ISSUE TITLE
recipe: yaml based assertion

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#6]
As a developer I want to use better assertion logic than the following:
```yaml
- name: Fetch OpenEBS control plane pods ready status
  shell: kubectl get pods -n openebs | grep {{ item }} | awk '{print $2}' | awk -F'/' '{print $1}' && kubectl get pods -n openebs | grep {{ item }} | awk '{print $2}' | awk -F'/' '{print $2}'
  register: ready_status
  with_items:
    - '{{ openebs_components }}'
  until: '{{ ready_status.stdout_lines | unique | length == 1 }}'
  retries: 20
  delay: 5
```
It will be great to assert list of values in a declarative manner. 

For example below yaml should be enough to assert any Pods with the given label to be in Running state. It should return error if there are any Pods that are not Running.
```yaml
kind: Pod
metadata:
  labels:
    name: app
status:
  phase: Running
```

**Comment by AmitKumarDas** [comment]
To further our expectation of declarative assertion, let us try to assert any Deployment that has one of its containers with a nginx image with name my-nginx.

The assertion yaml should look like below:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: my-nginx
        image: nginx
```

Assert any Deployment that has nginx image with container port 80
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - image: nginx
        ports:
        - containerPort: 80
```
