### ISSUE TITLE
proposal: PriorityConfig as a custom resource

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#64]
**ProblemStatement**: As a DevOps engineer, I want multiple k8s controllers to control setting of specifications of a target kubernetes resource. For example, controller-a is responsible to create a Pod resource. Controller-b is responsible to set taints & toleration policy against this Pod. Similarly, controller-c is responsible to set resource limits against this Pod. These controllers are responsible to manage specific fields of Pod resource. 

There are cases when multiple controllers may want to set same fields. In such a case, priority should be considered and the controller with maximum priority should set the value against the fields.

**Comment by AmitKumarDas** [comment]
```yaml
kind: PodConfig
metadata:
  name: memory
  namespace: blah
spec:
  state:
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "100Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
```

**Comment by sagarkrsd** [comment]
Great @AmitKumarDas, this can definitely help us in building the `openebs-operator` more robust and modular where we have a requirement to manage/handle the OpenEBS pod configurations wrt node selector, affinity, taints and a lot more.

**Comment by AmitKumarDas** [comment]
@sagarkrsd can you explain how exactly this can help? For example, can you list down the pain points that this solution tries to solve & i will try to fine tune the approach.

This approach considers both controller & users making their changes & the change that has higher priority gets accepted as the final state. For example this should help in arriving at the desired states for STS, Deployment, DaemonSet. 

Can this reduce the amount of code/boilerplate inn openebs upgrade?

**Comment by sagarkrsd** [comment]
When we say this(PodConfig) can be edited by users also, we should consider the case where it seems too generic and users would be more interested in providing the config at Deployment, DaemonSet, etc level instead of all the way coming down to pod.
For example, let's say I want my NDM pods to get deployed on a particular set of nodes or I want the NDM pods to use a specified amount of resources such as CPU, memory, etc and the other components to use some different values.

**Comment by sagarkrsd** [comment]
`openebs-upgrade` is responsible for deploying/managing OpenEBS components, hence it has the responsibility to form the desired manifest for all the OpenEBS components.

Some of the pain points that it can solve wrt `openebs-upgrade` are:

- Today, we have got a CR named `OpenEBS` which stores all the configuration wrt OpenEBS, it contains pod config for a particular component as well if a user wants to change it, the user needs to add that configuration in OpenEBS CR only.
If somehow the above proposal can help with the above i.e., maybe the user will get an option to form a particular component's podConfig separately, it would be very helpful.

- One of the challenges that we face while forming desired manifests for the OpenEBS components is handling the various pod configuration and that too based on the different container's config i.e., if a pod has multiple containers then forming the manifest(the code that goes into forming the manifest becomes a little cumbersome) becomes a little tedious and complex.

**Comment by AmitKumarDas** [comment]
If PodConfig becomes too generic we can have specific ones e.g. DeploymentConfig, STSConfig & so on. Users can edit these configs or provide new ones with priority & `podConfigResult.name`. The design is such that `n` no of `PodConfig`s get merged to a single PodConfigResult. 

Third party operators such as openebs upgrade will be looking out for specific `PodConfigResult` instance & make use of it to apply desired Pod or Deployment or STS etc.

**Comment by AmitKumarDas** [comment]
```yaml
  # PodBuilder will lookup various configs & optional existing Pod
  # resource to build a new Pod specification.
  kind: PodBuilder
  spec:
    # prefer Config over Pod or vice-versa
    # Config or Pod are valid values
    prefer:
    
    # selection may include one or more containers
    # they will be added/merged into the generated Pod spec based
    # on priorities assigned
    containerConfigSelector:
      matchLabels:
    
    # selection may include one or more tolerations
    # they will be merged into the generated Pod spec based
    # on priorities assigned
    tolerationsConfigSelector:
      matchLabels:
    
    # seelction should filter a single matching pod
    # it should warn if more than one pod are found
    podSelector:
      matchLabels:
    
    # the resource that is applied after pod spec is built
    # PodPreview is the default
    output: # PodPreview, or Pod
  status:
```
```yaml    
  # This will reflect one kubernetes Container spec
  kind: ContainerConfig
  metadata:
    name: CC-1
    labels:
      cstor: mgmt
  spec:
    priority:
    template:
      name:
      image: cstor-pool-mgmt
      command:
      args:
      env:
      resources:
        cpu:
        mem:
```
```yaml
  # This will reflect one kubernetes Container spec
  kind: ContainerConfig
  metadata:
    name: CC-2
    labels:
      cstor: monitor
  spec:
    priority:
    template:
      name:
      image: cstor-pool-monitor
      command:
      args:
      env:
      resources:
        cpu:
        mem:
```
```yaml
  # This will reflect one Kubernetes tolerations spec
  kind: TolerationsConfig
  metadata:
    name:
    namespace:
    labels:
  spec:
    priority
    template:
    - key:
      operator:
      effect:
      tolerationSeconds:
```
```yaml 
  # This will be the output of PodBuilder
  # PodBuilder might apply a Pod as well if set
  kind: PodPreview
  result:
```
