### ISSUE TITLE
embed jsonnet as one action in recipe

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#7]

**Comment by AmitKumarDas** [comment]
### Draft 0
```yaml
# refer metac for more details
kind: GenericController
spec:
  watch:
    resource: runs
  attachments:
  - resource: deployments
  - resource: pods
  - resource: xyzs
```
```yaml
kind: Run
spec:
  file
    name: my-ctrl.jsonnet
    path: /etc/config/blah
status:
```
```jsonnet
// code
```

### References:
- https://github.com/AmitKumarDas/metac/
- https://github.com/AmitKumarDas/metac/blob/master/examples/gctl/install-uninstall-crd/hooks/finalize-crd.jsonnet
- https://github.com/AmitKumarDas/metac/blob/master/examples/gctl/install-uninstall-crd/hooks/sync-crd.jsonnet

**Comment by AmitKumarDas** [comment]
As per latest thoughts, I am not pursuing jsonnet to design kubernetes controller. It seems feasible that a declarative controller can be implemented just with yaml(s).

**Comment by AmitKumarDas** [comment]
Back with requirements for jsonnet!

There are definite cases when given a set of kubernetes resources one can implement a jsonnet based logic to achieve a higher order requirement. Will jsonnet based logic suffice? Yes. It will be sufficient if the logic is limited to extracting values from available kubernetes resources and applying them against same or other kubernetes resources. In other words, jsonnet based logic works if this logic needs to deal only with json resource(s).

NOTE: apply implies either create or update

**_UseCase_**: As a cstor admin, I would like to move one of my cstor volume replicas from Pool1 to Pool2. Note that this cstor volume has three replicas spread over three pools where each pool resides on a particular Kubernetes node.

Lets try to understand if our assumption of **simple logic** is applicable for this use case.
We can implement a simple logic  use case on following assumptions:
-

**Comment by AmitKumarDas** [comment]
### Design Draft 1
_NOTE: kind: Recipe is taken already in this project_

```yaml
# We shall use Chef as the name of this new resource
# Chef implies someone who needs to cook food out of the
# ingredients. Here ingredients imply one or more kubernetes 
# resources (read json documents).
apiVersion: dope.metacontroller.io/v1alpha1
kind: Chef
metadata:
  name: cstor-volume-migration
  namespace: openebs
  labels:
    dope.metacontroller.io/storage-engine: cstor
    dope.metacontroller.io/feature: volume-migration
spec:
  configmapRef: # this configmap will hold the jsonnet logic
    name:
    namespace:
  values:
    key1: val2
    key2: val2
```

_NOTE: We shall be using [metac](https://github.com/AmitKumarDas/metac/) to take care of reconciliation needs_
_NOTE: We shall make use of GenericController from metac_
```yaml
kind: GenericController
metadata:
  name: migrate-cstor-volume
  labels:
    dope.metacontroller.io/storage-engine: cstor
    dope.metacontroller.io/feature: volume-migration
spec:
  watch:
    kind: dope.metacontroller.io/v1alpha1
    resource: chefs
  attachments:
  - kind: v1
    resource: nodes
  - kind: cstor.openebs.io/v1
    resource: cstorvolumeconfigs
  - kind: cstor.openebs.io/v1
    resource: cstorpoolinstances
```
