### ISSUE TITLE
proposal: recipe based reportcard custom controller

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#73]
**ProblemStatement**: A report card that provides various results w.r.t Recipe custom resources will be helpful. This report card can have passed, failed count. It can optionally have the detailed fail messages. This report card should be able to opt in or out Recipes based on label / annotation / name selectors.

**Comment by AmitKumarDas** [comment]
```yaml
kind: RecipeReportCard
metadata:
  name:
  namespace:
spec:
  selector:
    matchLabels:
    matchLabelExpressions:
  reportDetailsOn:
  - path: status.phase
  - path: status.taskResults.[*].warning
  - path: status.taskResults.[*].error
```
