### ISSUE TITLE
proposal: Log as a custom resource

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#74]
Draft specs:
```yaml
kind: Log
spec:
  targetPod:
    nameSelector:
    namespaceSelector:
    labelSelector:
    annotationSelector:
    advancedSelector:
  targetContainer:
    nameSelector:
    imageSelector:
  tailCount:
status:
```

```yaml
kind: LogOutput
output:
```

**Comment by AmitKumarDas** [comment]
### Design Draft 1
- How about having logs of associated pods in one place?

```yaml
kind: Log
spec:
  errors:
  - id:
    labelSelector:
    containerSelector:
    tailCount:
    grep:
    - operator: StartsWith
      value:
    - operator: Contains
      value:
status:
  phase:
  errors:
  - podName:
    podNamespace:
    containerName:
    logs: # top 3 errors are listed
    - message:
      count:
```
