### ISSUE TITLE
proposal: gitupload as a kubernetes custom resource

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#75]
**ProblemStatement**: As an automation engineer, I want to upload specific kubernetes resources as well as pod logs from a running kubernetes cluster to some github repo. This helps me to refer to these resources long after the kubernetes cluster is gone.

**Comment by AmitKumarDas** [comment]
Draft Specs:
```yaml
kind: GitUpload
spec:
  resources:
  - kind:
    apiVersion:
    selector:
      matchLabels:
      matchLabelExpressions:
  logs:
    podSelector:
      matchLabels:
      matchLabelExpressions:
      matchContainers:
      matchContainerExpressions:
```
