### ISSUE TITLE
chore: create an experiment to check the status of pod and its containers present in a namespace

### ISSUE THREAD

**Issue by harshshekhar15** [mayadata-io/d-operators#81]

**Comment by AmitKumarDas** [comment]
@harshshekhar15 can you try this _(this is just a sample, you might need to change if needed)_:

This does the following things:
- Asserts presence of pod `target-ns` `my-pod`
- Asserts this pod phase equals `Running`
- Asserts this pod has a container named my-con-1 with image nginx
- Asserts this pod has a container named my-con-2 with image dope

```yaml
apiVersion: metacontroller.app/v1
kind: Job
metadata:
  name: assert-my-use-case
  namespace: some-namespace
spec:
  tasks:
  - name: assert-my-pod
    assert: 
      state: 
        kind: Pod
        apiVersion: v1
        metadata:
          name: my-pod
          namespace: target-ns
        spec:
          containers:
          - name: my-con-1
            image: nginx
          - name: my-con-2
            image: dope
        status:
          phase: Running
```
