### ISSUE TITLE
feat: http and related custom resources

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#83]
**ProblemStatement**: As an automation engineer, I would like to convert my http requests into a declarative model. I would like to invoke one or more http requests. All these requests depend on secret to authentication the http server. In addition, some of the http requests are built from the response of successful http invocations.

**Comment by AmitKumarDas** [comment]
```yaml
kind: HTTPConfigBuilder
spec:
  httpSelector:
  - refer:
      name:
      kind: # optional
      apiVersion: # optional
    template:
    - from: status.output.abc # HTTP
      to: spec.data.abc # HTTPConfig
```
```yaml
kind: HTTPConfig
metadata:
  labels:
    abc: val
spec:
  data: # map[string]string
```
```yaml
kind: HTTPBuilder
spec:
  configSelector:
  - matchLabels: # should match all HttpConfigs with this label
      abc: val
  template:
    metadata:
    spec:
      secret:
      body:
      params:
```
```yaml
kind: HTTP
spec:
  secret:
  body:
  params:
```
