### ISSUE TITLE
kind:run as a controller to manage execution of tasks

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#9]
Problem Statement: I would like to have a simple declarative way to manage execution of various Kubernetes resources _(native as well as custom)_.

```yaml
kind: Run
spec:
  onError:
    retry:
      times:
      interval:
    abort: # true
  tasks:
  - desc:
    id: 
    state: # map[string]interface{}
    assert:
    - key: # json paths, etc. optional
      operator: # Equals, NotEquals, EqualsCount
      value: # string based values
      count: # int
    replicas: # when more than one states need to be created
    delete: # optional; WIP; THINK
      key:
      operator:
      value:
      count:
```
