### ISSUE TITLE
feat: proposal to implement a declarative kubernetes controller

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#95]
**ProblemStatement**: As a K8s engineer
- I want to watch a resource & update its status
- I want to watch more than one resources & update their status
- I want to watch multiple resources & update their labels
- I want to watch multiple resources & update their annotations
- I want to watch a resource & create one or more Kubernetes resources as the watch's desired state

**Comment by AmitKumarDas** [comment]
### Design Draft 0
_NOTE: kind: MasterChef will be the name of this new resource_
_NOTE: MasterChef will depend on existing Kubernetes custom & native resources to cook up a new requirement_
_NOTE: Jsonnet will be used to fill up the last mile automation_

**Comment by AmitKumarDas** [comment]
### Specifications Draft 0

#### Minimal specs
```yaml
kind: UberLoop
spec:
  parent:
  children:
  attachments:
  sync:
``` 

#### Detailed specs
```yaml
kind: UberLoop
spec:
  parent: # resource under watch; [optional]
    apiVersion:
    resource:
    selector:
  children: # resources due to parent; [optional]
  - apiVersion:
    resource:
    selector:
  attachments: # resources that may or may not be related to parent; [optional]
  - apiVersion:
    resource:
    selector:
  sync:
    jsonnet: # use kind: ConfigMap resources
      labelSelector:
    command: # use kind: Command resources
      labelSelector:
```
