### ISSUE TITLE
feat: custom controller to simplify api testing

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/d-operators#99]
**_ProblemStatement_**: As an automation engineer I want to verify my use case by testing its REST APIs. Most of the times, a feature consists of one or more invocations to REST APIs. Some of these APIs need to parse output from previous API invocations. All of these APIs need some kind of authentication to succeed.

**Comment by AmitKumarDas** [comment]
### Design Draft 0

#### Brief Schema
```yaml
kind: HTTPPipe
spec:
  steps:
  - call:
  - build:
```

#### Expanded Schema
```yaml
kind: HTTPPipe
spec:
  steps:
  - call:
      http:
        url:
        method:
        pathParams:
        - key:
          value:
        queryParams:
        - key:
          value:
  - build: # builds the body
    - key: 
      value:
    - keyNested: # e.g. employee.name
      valueFrom: # extract value from some previous response
    - yaml: # body in yaml format; merged with all key:value pairs found inside build
  - call:
  - build:
  - call:
  - call:
```

**Comment by AmitKumarDas** [comment]
### Design Draft 1
#### Brief Schema
```yaml
kind: HTTPPipe
spec:
  given: # holds key value pairs
  begin: # first http invocation
    request:
  then: # subsequent http invocation
  - request:
    onResponse:
```

#### Expanded Schema
```yaml
kind: HTTPPipe
spec:
  given: # holds key value pairs
  begin: # first http invocation
    request:
      url:
      pathParams:
      queryParams:
      data:
        state:
        fromPath:
    retry:
      onError:
      onMismatch:
      onMismatchExpressions:
  then: # subsequent http invocation
  - request:
    onResponse:
      buildData:
        fromState:
        fromPairs:
        - key:
          value:
        - keyNested: field1.field2.field3
          valueFrom: # jsonpath that returns a value
          default:
    retry:
      onError:
      onMismatch:
      onMismatchExpressions:
```
